spring.application.name=text-to-sql

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/nexacorp
spring.datasource.username=root
spring.datasource.password=root
